#
# Copyright © 2013-2019, The SeedStack authors <http://seedstack.org>
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

logging: INFO
jcr:
  defaultRepository: default
  sessions:
    default:
      type: LOCAL_PATH
      address: ./target/test/repositories/jcr1
      username: admin
      password: admin
    alternative:
      type: LOCAL_PATH
      address: ./target/test/repositories/jcr2
      vendorProperties:
        prop1: value