#
# Copyright (c) 2013-2016, The SeedStack authors <http://seedstack.org>
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

logging: INFO
jcr:
  defaultRepository: default
  sessions:
    default:
      type: LOCAL_PATH
      address: /temp/jcr1
    alternative:
      type: LOCAL_PATH
      address: /temp/jcr2